service: money-sync-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    CLIENT_URL: ${env:CLIENT_URL}

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins: []
