import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_STORAGE_KEY = "app_language";
const FALLBACK_LANGUAGE = "en";
const SUPPORTED_LANGUAGES = new Set(["en", "he"]);

const MESSAGES = {
  en: {
    appTitle: "Money Sync",
    dashboard: "Dashboard",
    shoppingLists: "Shopping Lists",
    bank: "Bank",
    account: "Account",
    logout: "Logout",
    language: "Language",
    english: "English",
    hebrew: "Hebrew",
    englishWithFlag: "🇺🇸 USA - English",
    hebrewWithFlag: "🇮🇱 Israel - Hebrew",
    login: "Login",
    createAccount: "Create account",
    register: "Register",
    switchToLogin: "Switch to login",
    switchToRegister: "Switch to register",
    name: "Name",
    email: "Email",
    password: "Password",
    allExpenses: "All expenses",
    amount: "Amount",
    pendingStatus: "Pending",
    postedStatus: "Posted",
    pendingStatusTooltip:
      "This transaction is pending and may change when the bank finalizes it.",
    installmentsStatePrefix: "Installments",
    installmentsStateLabel: "Installments state",
    installmentsStateNotCharged: "Not charged yet",
    installmentsStateCharged: "Charged",
    installmentProgressLabel: "Installment",
    role: "Role",
    description: "Description",
    category: "Category",
    save: "Save",
    reviewed: "Reviewed",
    source: "Source",
    merchant: "Merchant",
    externalId: "External ID",
    yes: "Yes",
    no: "No",
    all: "All",
    tags: "Tags",
    notes: "Notes",
    created: "Created",
    createdAtLabel: "Created at:",
    updated: "Updated",
    showDetails: "Show details",
    hideDetails: "Hide details",
    logoutConfirmMessage: "Are you sure?",
    cancel: "Cancel",
    edit: "Edit",
    changedByUser: "Changed",
    saveChanges: "Save changes",
    descriptionRequired: "Description is required",
    failedUpdateExpense: "Failed to update expense",
    date: "Date",
    categoryFilter: "Category",
    timeRange: "Time range",
    thisMonth: "This month",
    lastMonth: "Last month",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    customRange: "Custom range",
    allTime: "All time",
    startDate: "Start date",
    endDate: "End date",
    invalidDateRange: "Start date must be before or equal to end date.",
    allCategories: "All categories",
    sortBy: "Sort by",
    accountFilter: "Card/Account",
    allAccounts: "All accounts",
    sortDateNewest: "Date: newest first",
    sortDateOldest: "Date: oldest                 first",
    sortPriceHighToLow: "Price: high to low",
    sortPriceLowToHigh: "Price: low to high",
    amountRange: "Amount range",
    summaryItems: "items",
    summaryTotal: "Summary total",
    summaryDates: "Dates",
    general: "General",
    createShoppingList: "Create shopping list",
    title: "Title",
    weeklyGroceries: "Weekly groceries",
    create: "Create",
    done: "Done",
    markDone: "Mark done",
    sampleMilk: "Milk",
    sampleBread: "Bread",
    bankCredentials: "Bank credentials",
    configureBankCredentials:
      "Configure credentials used by bank sync for your account.",
    status: "Status",
    loading: "Loading...",
    loadingBankExpensesPrefix: "Loading",
    loadingBankExpensesSuffix: "expenses...",
    loadingBankExpensesDefault: "Loading bank expenses...",
    connected: "Connected",
    connectedAccounts: "Connected accounts:",
    notConnected: "Not connected",
    lastUpdated: "Last updated",
    lastBankFetch: "Last bank fetch",
    configuredAccounts: "Configured accounts",
    noBankConnections: "No bank accounts connected yet.",
    dashboardNoBankConnectionMessage:
      "No bank connection is configured for your account. Go to the Bank page to connect one.",
    unnamedConnection: "Unnamed connection",
    addConnection: "Add account",
    connectionName: "Account nickname",
    connectionVisibility: "Connection visibility",
    cardVisibility: "Card visibility",
    billingDate: "Billing date",
    cardEndingWith: "Card ending with:",
    sharedConnection: "Shared (all household members)",
    privateConnection: "Private (only me)",
    noConnectionCardsDetected: "No cards detected yet for this connection.",
    cardVisibilitySaved: "Card visibility saved.",
    failedSaveCardVisibility: "Failed to save card visibility",
    cardSettingsSaved: "Card settings saved.",
    failedSaveCardSettings: "Failed to save card settings",
    removeConnection: "Remove",
    removeAllConnections: "Remove all",
    bankOrCreditCardCompany: "Bank / Credit Card Company",
    required: "Required",
    optional: "Optional",
    saveCredentials: "Save credentials",
    disconnect: "Disconnect",
    bankCredentialsSaved: "Bank credentials saved.",
    bankCredentialsRemoved: "Bank credentials removed.",
    bankConnectionSaved: "Bank account added.",
    bankConnectionRemoved: "Bank account removed.",
    allBankConnectionsRemoved: "All bank accounts removed.",
    failedLoadBankStatus: "Failed to load bank connection status",
    failedSaveBankCredentials: "Failed to save bank credentials",
    syncConnection: "Sync connection",
    connectionSyncCompleted: "Connection sync completed.",
    failedTriggerConnectionSync: "Failed to sync bank connection",
    failedRemoveBankConnection: "Failed to remove bank account",
    failedRemoveBankCredentials: "Failed to remove bank credentials",
    removeSelectedBankConnectionConfirm:
      "This will remove the selected bank connection.",
    removeAllBankConnectionsConfirm:
      "This will remove all configured bank connections.",
    defaultBankAccountsDescription:
      "Choose which bank accounts are selected by default in the dashboard filter.",
    defaultBankAccountsSectionTitle: "Default dashboard accounts",
    accountDefaultsSaved: "Default bank account selection saved.",
    failedSaveAccountDefaults: "Failed to save default bank account selection",
    failedLoadAccountDefaults: "Failed to load account defaults",
    bankManagerOnlyMessage:
      "Only household managers can add or remove bank connections.",
    householdMembers: "Household members",
    myUserInfo: "My info",
    theme: "Theme",
    themeSectionDescription:
      "Choose your app color scheme. Changes are saved in this browser only.",
    colorScheme: "Color scheme",
    managerRole: "Manager",
    memberRole: "Member",
    inviteToHousehold: "Invite user to household",
    sendInvite: "Send invite",
    inviteHint: "Invite an existing user by email to join your household.",
    householdInvitations: "My invitations",
    noPendingInvitations: "No pending invitations.",
    inviteFrom: "Invite from:",
    joinHousehold: "Join household",
    householdInviteSent: "Invitation sent.",
    failedInviteUser: "Failed to send invitation",
    householdJoined: "You joined the household.",
    failedJoinHousehold: "Failed to join household",
    failedSaveItemNote: "Failed to save item note",
    inviteEmailRequired: "Email is required",
    deleteListConfirmMessage:
      "Are you sure you want to delete the {listName} list?",
    newListButton: "+ New list",
    editListTitle: "Edit list",
    newItemButton: "+ New item",
    itemName: "Item name",
    itemQuantity: "Quantity",
    itemsCountLabel: "items",
    addNote: "Add note",
    note: "Note",
  },
  he: {
    appTitle: "Money Sync",
    dashboard: "לוח בקרה",
    shoppingLists: "רשימות קניות",
    bank: "בנק",
    account: "חשבון",
    logout: "התנתק",
    language: "שפה",
    english: "אנגלית",
    hebrew: "עברית",
    englishWithFlag: "🇺🇸 ארצות הברית - אנגלית",
    hebrewWithFlag: "🇮🇱 ישראל - עברית",
    login: "התחברות",
    createAccount: "יצירת חשבון",
    register: "הרשמה",
    switchToLogin: "מעבר להתחברות",
    switchToRegister: "מעבר להרשמה",
    name: "שם",
    email: "אימייל",
    password: "סיסמה",
    allExpenses: "כל ההוצאות",
    amount: "סכום",
    pendingStatus: "ממתין",
    postedStatus: "חויב",
    pendingStatusTooltip: "העסקה עדיין ממתינה ועשויה להשתנות לאחר אישור סופי מהבנק.",
    installmentsStatePrefix: "עסקת תשלומים",
    installmentsStateLabel: "מצב עסקת תשלומים",
    installmentsStateNotCharged: "טרם חויבה",
    installmentsStateCharged: "חויבה",
    installmentProgressLabel: "תשלום",
    role: "תפקיד",
    description: "תיאור",
    category: "קטגוריה",
    save: "שמירה",
    reviewed: "נבדק",
    source: "מקור",
    merchant: "בית עסק",
    externalId: "מזהה חיצוני",
    yes: "כן",
    no: "לא",
    all: "הכל",
    tags: "תגיות",
    notes: "הערות",
    created: "נוצר",
    createdAtLabel: "נוצר בתאריך:",
    updated: "עודכן",
    showDetails: "הצג פרטים",
    hideDetails: "הסתר פרטים",
    logoutConfirmMessage: "האם אתה בטוח?",
    cancel: "ביטול",
    edit: "עריכה",
    changedByUser: "שונה",
    saveChanges: "שמירת שינויים",
    descriptionRequired: "תיאור הוא שדה חובה",
    failedUpdateExpense: "עדכון ההוצאה נכשל",
    date: "תאריך",
    categoryFilter: "קטגוריה",
    timeRange: "טווח זמן",
    thisMonth: "החודש",
    lastMonth: "חודש קודם",
    last7Days: "7 ימים אחרונים",
    last30Days: "30 ימים אחרונים",
    customRange: "טווח מותאם",
    allTime: "כל הזמן",
    startDate: "תאריך התחלה",
    endDate: "תאריך סיום",
    invalidDateRange: "תאריך ההתחלה חייב להיות לפני או שווה לתאריך הסיום.",
    allCategories: "כל הקטגוריות",
    sortBy: "מיון לפי",
    accountFilter: "כרטיס/חשבון",
    allAccounts: "כל החשבונות",
    sortDateNewest: "תאריך: מהחדש לישן",
    sortDateOldest: "תאריך: מהישן לחדש",
    sortPriceHighToLow: "מחיר: מהגבוה לנמוך",
    sortPriceLowToHigh: "מחיר: מהנמוך לגבוה",
    amountRange: "טווח סכום",
    summaryItems: "מספר פריטים",
    summaryTotal: "סכום בסיכום",
    summaryDates: "תאריכים",
    general: "כללי",
    createShoppingList: "יצירת רשימת קניות",
    title: "כותרת",
    weeklyGroceries: "קניות שבועיות",
    create: "יצירה",
    done: "בוצע",
    markDone: "סמן כבוצע",
    sampleMilk: "חלב",
    sampleBread: "לחם",
    bankCredentials: "פרטי התחברות לבנק",
    configureBankCredentials:
      "הגדר את פרטי ההתחברות לסנכרון הבנק עבור החשבון שלך.",
    status: "סטטוס",
    loading: "טוען...",
    loadingBankExpensesPrefix: "טוען הוצאות של",
    loadingBankExpensesSuffix: "...",
    loadingBankExpensesDefault: "טוען הוצאות בנק...",
    connected: "מחובר",
    connectedAccounts: "חשבונות מחוברים:",
    notConnected: "לא מחובר",
    lastUpdated: "עודכן לאחרונה",
    lastBankFetch: "סנכרון אחרון",
    configuredAccounts: "חשבונות מוגדרים",
    noBankConnections: "עדיין לא חוברו חשבונות בנק.",
    dashboardNoBankConnectionMessage:
      "לא הוגדר חיבור בנק עבור החשבון שלך. עבור לעמוד הבנק כדי לחבר חשבון.",
    unnamedConnection: "חיבור ללא שם",
    addConnection: "הוספת חשבון",
    connectionName: "כינוי לחשבון",
    connectionVisibility: "נראות החיבור",
    cardVisibility: "נראות כרטיס",
    billingDate: "תאריך חיוב",
    cardEndingWith: "כרטיס המסתיים ב:",
    sharedConnection: "משותף (כל חברי משק הבית)",
    privateConnection: "פרטי (רק אני)",
    noConnectionCardsDetected: "עדיין לא זוהו כרטיסים עבור חיבור זה.",
    cardVisibilitySaved: "נראות הכרטיס נשמרה.",
    failedSaveCardVisibility: "שמירת נראות הכרטיס נכשלה",
    cardSettingsSaved: "הגדרות הכרטיס נשמרו.",
    failedSaveCardSettings: "שמירת הגדרות הכרטיס נכשלה",
    removeConnection: "הסרה",
    removeAllConnections: "הסר הכל",
    bankOrCreditCardCompany: "בנק / חברת אשראי",
    required: "חובה",
    optional: "אופציונלי",
    saveCredentials: "שמירת פרטי התחברות",
    disconnect: "ניתוק",
    bankCredentialsSaved: "פרטי ההתחברות לבנק נשמרו.",
    bankCredentialsRemoved: "פרטי ההתחברות לבנק הוסרו.",
    bankConnectionSaved: "חשבון בנק נוסף בהצלחה.",
    bankConnectionRemoved: "חשבון הבנק הוסר.",
    allBankConnectionsRemoved: "כל חשבונות הבנק הוסרו.",
    failedLoadBankStatus: "טעינת סטטוס החיבור לבנק נכשלה",
    failedSaveBankCredentials: "שמירת פרטי ההתחברות לבנק נכשלה",
    syncConnection: "סנכרון חיבור",
    connectionSyncCompleted: "סנכרון החיבור הושלם.",
    failedTriggerConnectionSync: "סנכרון חיבור הבנק נכשל",
    failedRemoveBankConnection: "הסרת חשבון הבנק נכשלה",
    failedRemoveBankCredentials: "הסרת פרטי ההתחברות לבנק נכשלה",
    removeSelectedBankConnectionConfirm: "הפעולה תסיר את חיבור הבנק שנבחר.",
    removeAllBankConnectionsConfirm: "הפעולה תסיר את כל חיבורי הבנק שהוגדרו.",
    defaultBankAccountsDescription:
      "בחר אילו חשבונות בנק יהיו מסומנים כברירת מחדל במסנן בלוח הבקרה.",
    defaultBankAccountsSectionTitle: "חשבונות ברירת מחדל ",
    accountDefaultsSaved: "ברירת המחדל של חשבונות הבנק נשמרה.",
    failedSaveAccountDefaults: "שמירת ברירת המחדל של חשבונות הבנק נכשלה",
    failedLoadAccountDefaults: "טעינת ברירות המחדל של החשבון נכשלה",
    bankManagerOnlyMessage:
      "רק מנהלי משק בית יכולים להוסיף או להסיר חיבורי בנק.",
    householdMembers: "חברי משק הבית",
    myUserInfo: "הפרטים שלי",
    theme: "ערכת נושא",
    themeSectionDescription:
      "בחר את ערכת הצבעים של האפליקציה. השינוי נשמר בדפדפן זה בלבד.",
    colorScheme: "ערכת צבעים",
    managerRole: "מנהל",
    memberRole: "חבר",
    inviteToHousehold: "הזמנת משתמש למשק הבית",
    sendInvite: "שלח הזמנה",
    inviteHint: "הזמן משתמש קיים לפי אימייל להצטרף למשק הבית.",
    householdInvitations: "ההזמנות שלי",
    noPendingInvitations: "אין הזמנות ממתינות.",
    inviteFrom: "הזמנה מאת:",
    joinHousehold: "הצטרף למשק הבית",
    householdInviteSent: "ההזמנה נשלחה.",
    failedInviteUser: "שליחת ההזמנה נכשלה",
    householdJoined: "הצטרפת למשק הבית.",
    failedJoinHousehold: "הצטרפות למשק הבית נכשלה",
    failedSaveItemNote: "שמירת הערת הפריט נכשלה",
    inviteEmailRequired: "אימייל הוא שדה חובה",
    deleteListConfirmMessage: "האם למחוק את רשימת {listName}?",
    newListButton: "+ רשימה חדשה",
    editListTitle: "עריכת רשימה",
    newItemButton: "+ הוסף פריט",
    itemName: "שם פריט",
    itemQuantity: "כמות",
    itemsCountLabel: "פריטים",
    addNote: "הוסף הערה",
    note: "הערה",
  },
};

const LanguageContext = createContext(null);

function getInitialLanguage() {
  const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  if (saved && SUPPORTED_LANGUAGES.has(saved)) {
    return saved;
  }
  return FALLBACK_LANGUAGE;
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);
  const direction = language === "he" ? "rtl" : "ltr";

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
    document.body.dir = direction;
  }, [language, direction]);

  const value = useMemo(
    () => ({
      language,
      direction,
      locale: language === "he" ? "he-IL" : "en-US",
      setLanguage,
      t: (key) => MESSAGES[language]?.[key] || MESSAGES.en[key] || key,
    }),
    [direction, language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
